
package com.oracle.csm.soapwsexample.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "http://soapwstemplate.csm.oracle.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://soapwstemplate.csm.oracle.com/", className = "com.oracle.csm.soapwsexample.client.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://soapwstemplate.csm.oracle.com/", className = "com.oracle.csm.soapwsexample.client.SayHelloWorldResponse")
    @Action(input = "http://soapwstemplate.csm.oracle.com/HelloWorldPortType/sayHelloWorldRequest", output = "http://soapwstemplate.csm.oracle.com/HelloWorldPortType/sayHelloWorldResponse")
    public String sayHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
